"""add plan to users

Revision ID: 2450cf6f398e
Revises: 772439c7847b
Create Date: 2026-07-26 17:39:52.604879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2450cf6f398e'
down_revision: Union[str, None] = '772439c7847b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plan', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plan')
    # ### end Alembic commands ###
